name: sehatinapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  intl: ^0.20.2
  google_fonts: ^6.2.1
  color: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  image_picker: ^1.1.2
  flutter_secure_storage: ^9.2.4
  flutter_gen_runner: ^5.10.0
  flutter_svg: ^2.1.0
  share_plus: ^11.0.0
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  google_sign_in: ^6.3.0
  draggable_scrollbar: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/poster.png
    - assets/images/bingung.png
    - assets/images/bahagia.png
    - assets/images/kesal.png
    - assets/images/sedih.png
    - assets/images/senang.png
    - assets/images/netral.png
    - assets/images/image.png
    - assets/images/image (1).png
    - assets/images/image (2).png
    - assets/images/image (3).png
    - assets/images/image (4).png
    - assets/images/image_placeholder.png 
    - assets/google.png
    - assets/logout.png
